### ISSUE TITLE
Create header section

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Portfolio#4]
## Goal
-  Header section has 4 links (home, works, skills, contact) on the top of the screen
## Deadline / Task size
- 0.5day
## Steps
- Create navigation bar on the middle off the screen (home, works, skills, contact)
- To implement hover effects on the links for visibility
- Fix the header section on the top of the screen
- Create a blurred header background
## Uncertainty
- How to fix the header section on the top of the screen
- How to blur header background

## Additional memo
-

**Comment by HidemichiShimura** [comment]
> create header section

This is a step to solve this issue, not the goal itself.

> set hover to change text color when selected

What exactly are you implementing the hover effect on?

> fix the header section

What are you fixing about the header?

> how to fix the header section

Same above.
It would be better if you described each topic in detail like specifying items you implement the hover effect on and what you are trying to fix about the header.

**Comment by yurihoka** [comment]
> This is a step to solve this issue, not the goal itself.

done


> What exactly are you implementing the hover effect on?


To implement hover effects on the links for visibility. done

> What are you fixing about the header?


fix it on the top of screen. done

> It would be better if you described each topic in detail like specifying items you implement the hover effect on and what you are trying to fix about the header.

noted

**Comment by yurihoka** [comment]
Change/add below items.

> Goal

Change : 3 links (home, works, contact)→4 links (home, works, skills, contact)

> Steps

Add : Create a blurred header background

> Uncertainly

Add : How to blur header background
